---
title: "airbnb_analysis"
author: "Collin"
date: "4/22/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(readr)
library(nsprcomp)
library(predictrace)
library(ggmap) #used to make heatmaps
library(glmnet)
library(leaflet)
library(httr)
?leaflet

#POSSIBLE QUESTIONS:
#Can we classify 



```


#Wrangling Data
```{r}
airbnb_data = read_csv("Airbnb_NYC_2019.csv")
airbnb_data = airbnb_data %>% na.omit() %>% 
  mutate(pred_race = predict_race(host_name))


airbnb_data = airbnb_data %>% 
  mutate(pred_race_probability =
           case_when( pred_race$likely_race == "white" ~ pred_race$probability_white,
                      pred_race$likely_race == "asian" ~ pred_race$probability_asian,
                      pred_race$likely_race == "black" ~ pred_race$probability_black,
                      pred_race$likely_race == "hispanic" ~ pred_race$probability_hispanic,
                      pred_race$likely_race == "american_indian" ~ pred_race$probability_american_indian,
                      pred_race$likely_race == "other" ~ pred_race$probability_2races
           )) %>% 
  mutate(predicted_race =
           case_when( pred_race$likely_race == "white" ~ "white",
                      pred_race$likely_race == "asian" ~ "asian",
                      pred_race$likely_race == "black" ~ "black",
                      pred_race$likely_race == "hispanic" ~ "hispanic",
                      pred_race$likely_race == "american_indian" ~ "american indian",
                      pred_race$likely_race == "black, white" ~ "other"
           )) %>% select(-pred_race) %>%
  mutate(price_range = case_when(
    (price >= 0 & price < 100) ~ "0-99",
    price >= 100 & price < 300 ~ "100-299",
    price >=300 & price < 500 ~ "300-499",
    price >=500 & price < 700 ~ "500 - 699",
    price >= 700 & price < 1000 ~ "700-999",
    (price >= 1000 & price < 2500) ~ "1000-2499",
    price >= 2500 & price < 5000 ~ "2500-4999",
    price >= 5000 & price < 7500 ~ "5000-7499",
    price >= 7500 & price <=10000 ~ "7500-10000"
  )) %>% na.omit()

airbnb_data$price_range = factor(airbnb_data$price_range, levels = c("0-99", "100-299", "300-499",
                                                                     "500 - 699", "700-999","1000-2499",
                                                                     "2500-4999","5000-7499",
                                                                    "7500-10000"))

?colour_scale_gradient

airbnb_data %>% 
  group_by(room_type) %>% 
  summarize(distinct_neighborhoods = n())
```



```{r}
#use predictedrace package
#not sure what changed here



#how many of each predicted race?
airbnb_data %>% na.omit() %>% 
  group_by(predicted_race) %>% 
  summarize(number_each_race = n()) %>% 
  arrange(desc(number_each_race))


#do the proportions of race in the sample reflect census data? are certain races over or under represented in Airbnb data?
# if so, do these differences reflect some sort of racial bias in homeownership?


#number of distinct neighborhoods
# airbnb_data %>% 
#   group_by(neighbourhood) %>% 
#   summarize(number_of_neighborhoods = n_distinct(neighbourhood))


# airbnb_data = airbnb_data %>% 
#   mutate(price_range = case_when(
#     (price >= 0 & price < 100) ~ "0-99",
#     price >= 100 & price < 300 ~ "100-299",
#     price >=300 & price < 500 ~ "300-499",
#     price >=500 & price < 700 ~ "500 - 699",
#     price >= 700 & price < 1000 ~ "700-999",
#     (price >= 1000 & price < 2500) ~ "1000-2499",
#     price >= 2500 & price < 5000 ~ "2500-4999",
#     price >= 5000 & price < 7500 ~ "5000-7499",
#     price >= 7500 & price <=10000 ~ "7500-10000"
#   ))




airbnb_data %>% 
  group_by(price_range) %>% 
  summarize(count = n())

# airbnb_data %>% 
#   group_by(price) %>% 
#   summarize(count = n())
```

```{r}
colors = c("cyan1", "cyan2", "cyan3", "cyan4", "blue1", "blue2", "blue3", "blue4", "blueviolet")
# names(colors) = levels(airbnb_data$price_range)
names(colors) <- levels(factor(c(levels(airbnb_data$price_range)))) # Extract all levels of both data

colors
my_scale = scale_fill_manual(name = airbnb_data$price_range, values = colors)


airbnb_data %>% ggplot(mapping = aes(x = price_range,y = price))+
  geom_boxplot()



ggplot(data = airbnb_data, mapping = aes(x = price_range)) +
geom_bar() + scale_color_manual(values = c("0-99" = "purple",
                                "versicolor"="orange",
                                "virginica"= "steelblue"))+theme_minimal()

  
ggplot(data = airbnb_data, mapping = aes(x = price_range)) +
  geom_bar(fill = colors)

airbnb_data %>% 
  group_by(predicted_race) %>% 
  summarize()




#colors for predicted_race map
colors_predicted_race = c("blue", "mediumorchid2", "orange", "yellow2", "green4")
names(colors) <- levels(factor(c(levels(airbnb_data$predicted_race))))

ggplot(data = airbnb_data, mapping = aes(x = predicted_race)) +
  geom_bar(fill = colors_predicted_race)

```



```{r}
#exploratory analysis- Price vs Neighbourhood

ggplot(data = airbnb_data, aes(x=neighbourhood_group, y=price, fill = room_type )) + 
  geom_bar(stat="identity", position=position_dodge()) +
  ggtitle("Price  vs. Neighborhood")+
  xlab("Neighborhood Group") + ylab("Price") + theme_minimal()


#confirming the plot reaches the max price of each neighbourhood group
airbnb_data %>% select(price, room_type, neighbourhood_group) %>% 
  group_by(neighbourhood_group,room_type) %>% 
  summarize(max_price = max(price)) %>% 
  filter(neighbourhood_group == "Staten Island")
```


```{r}
#exploratory data analysis - count of listing type by Borough (neighbourhood group)
ggplot(data = airbnb_data, aes(x=neighbourhood_group, y=price, fill = room_type )) + 
  geom_bar(stat="identity", position=position_dodge()) +
  ggtitle("Price  vs. Borough (Neighbourhood Group)")+
  xlab("Borough") + ylab("Price") + theme_minimal()


airbnb_data %>% 
  group_by(neighbourhood_group) %>% 
  count(room_type) %>% 
  mutate(pct = n / sum(n)) %>% 
  ggplot(aes(x = neighbourhood_group, pct, fill = room_type)) +
  geom_col(position = 'dodge')+
  scale_y_continuous(labels = scales::percent_format()) + ylim(0,1)+
  ylab("Percentage") + xlab("Neighbourhood") + ggtitle("Count of Listing Type by Neighbourhood")





```
```{r}
#average price by borough
airbnb_data %>% 
  group_by(neighbourhood_group,room_type) %>% 
  summarize(avg_price = mean(price)) %>% 
  ggplot(mapping = aes(x = neighbourhood_group, y = avg_price, fill = room_type))+
  geom_bar(stat = "identity",color = "white",position = position_dodge())+
  geom_text(aes(label=round(avg_price,2)), vjust=1.6, color="black",position = position_dodge(0.9), size=3.5)+
  ggtitle("Average Price of Airbnb Rental in each Borough",subtitle = "by Room Type " )+
  xlab("Borough") + ylab("Average Price")+
  theme_minimal()




```


```{r}

```





```{r}
#Yannian's Heat Map:
#Room Type on X Axis, Price Range on Y axis, count is our "third dimension"
#heat map tells us that private rooms in the $50-$100 per night range is the overwhelming majority of airbnb rentals (at least in this dataset.)
#Entire homes, which seem to be the second most common, are unsurprisingly higher price range of about $100-200 per night.

airbnb = read.table("Airbnb_NYC_2019.csv", header = TRUE, sep = ",", quote = "\"", comment.char = "")
airbnb$last_review = as.Date(airbnb$last_review)
airbnb$neighbourhood_group = as.factor(airbnb$neighbourhood_group)

#creating a map
#The key is linked to my school account and is free of use for 90 days.
register_google(key = "AIzaSyAIOXS__eabiuvNQxuJDZYauMmecXmJeQQ")
p <- ggmap(get_googlemap(center = c(lon = -73.96353, lat = 40.7895),
                         zoom = 10, scale = 4,
                         maptype ='terrain',
                         color = 'color'))
#plot each listing on map
p + geom_point(aes(x = longitude, y = latitude, colour = room_type), data = airbnb, size = 0.5)

#only plotting neighborhood_group Manhattan
Manhattan = airbnb %>% filter(neighbourhood_group == "Manhattan")
pm <- ggmap(get_googlemap(center = c(lon = mean(Manhattan$longitude), lat = mean(Manhattan$latitude)),
                          zoom = 11, scale = 4,
                          maptype ='terrain',
                          color = 'color'))
pm + geom_point(aes(x = longitude, y = latitude, colour = room_type), data = Manhattan, size = 0.5) +
  xlab('Longitude') +
  ylab('Latitude')

#heat map contingency table

#grouping data
price_neighbour = airbnb %>%
  group_by(neighbourhood_group, price_range=cut(price, breaks= seq(0, 500, by = 50), right=F)) %>%
  summarise(count = length(neighbourhood_group), price = mean(price)) %>%
  arrange(as.numeric(price_range))

price_roomType = airbnb %>%
  group_by(room_type, price_range=cut(price, breaks= seq(0, 500, by = 50), right=F)) %>%
  summarise(count = length(room_type), price = mean(price)) %>%
  arrange(as.numeric(price_range))
#changeing NA to [500,)
price_neighbour$price_range = as.character(price_neighbour$price_range)
price_neighbour$price_range[is.na(price_neighbour$price_range)] = "[500,)"
price_neighbour$price_range = as.factor(price_neighbour$price_range)
#making plots
ggplot(price_neighbour, aes(x = neighbourhood_group, y = price_range)) +
  geom_tile(aes(fill = count)) + 
  geom_text(aes(label = count)) +
  scale_fill_gradient2(low = 'white', high = 'dark red') +
  xlab("Neighbourhood Group") +
  ylab("Price Range")

ggplot(price_roomType, aes(x = room_type, y = price_range)) +
  geom_tile(aes(fill = count)) + 
  scale_fill_gradient2(low = 'white', high = 'dark red')




```


```{r}
#OLS
olsmod <- lm(data = train, price~as.factor(neighbourhood_group) + as.factor(predicted_race))
summary(olsreg)
stargazer(olsreg, type = "text")
pred <- predict(olsmod, data = test)
compare <- cbind(actual = test$price, pred)

```

```{r}
#Ridge Regression
library(glmnet)
y <- airbnb_data$price %>% na.omit()
length(y)
x <- airbnb_data %>% select(-price) %>% data.matrix()

x <- model.matrix(airbnb_data~ . - price, airbnb_data)
apply(airbnb_data,2,length)
lambdas <- 10^seq(3, -2, by = -.1)

fit <- glmnet(x, y, alpha = 0, lambda = lambdas)
summary(fit)






airbnb_data <- airbnb_data %>% na.omit()
train <- airbnb_data %>% sample_frac(.8)
test <- airbnb_data %>% setdiff(train)
xtrain <- sparse.model.matrix(price~., data = train)
xtest <- sparse.model.matrix(price~., data = test)

ytrain <- train %>% select(price) %>% unlist() %>% as.numeric()
ytest <- test %>% select(price) %>% unlist() %>% as.numeric()

grid <- 10^seq(10,-2,length = 100)
ridgemod <- glmnet(xtrain,ytrain, alpha = 0, lambda = grid)
plot(ridgemod)
ridge_cv <- cv.glmnet(xtrain, ytrain, alpha = 0)
best_lam <- ridge_cv$lambda.min
best_model <- ridge_cv$glmnet.fit
bestridge <- glmnet(xvars, yvars, alpha = 0, lambda = best_lam)

newX <- sparse.model.matrix(~.-price, data = test)
newX = as.matrix(newX) %>% as.data.frame()

pred <- predict(bestridge, s = best_lam, newx = newX)




```

```{r}
#Yannian's Ridge
library(glmnet)
set.seed(123)
sample_size = floor(0.8 * nrow(airbnb_data))

train_ind = sample(seq_len(nrow(airbnb_data)), size = sample_size)

train = airbnb_data[train_ind, ]
test = airbnb_data[-train_ind, ]

xtrain = train %>% select(-id,-name,-host_id,-host_name,-price) %>% data.matrix()
ytrain = train$price

xtest = test %>% select(-id,-name,-host_id,-host_name,-price) %>% data.matrix()
ytest = test$price

lambdas <- 10^seq(2, -3, by = -.1)

ridge_model = glmnet(xtrain, ytrain, nlambda = 25, family = 'gaussian', lambda = lambdas)

ridge_model

ridge_cv = cv.glmnet(xtrain, ytrain, alpha = 0, lambda = lambdas)
best_lam = ridge_cv$lambda.min

ridge_cv
best_lam

pred = predict(ridge_model, s = best_lam, newx = xtest)

#SSE
SSE = sum((pred - ytest)^2)
SST = sum((ytest - mean(ytest))^2)
RSquared = 1 - (SSE/SST)
RSquared
```


```{r}
#pie chart for predicted race by neighborhood
#Brooklyn 


# Stacked + percent
ggplot(barplot_data, aes(fill=predicted_race, y=value, x=neighbourhood_group)) + 
    geom_bar(position="fill", stat="identity") +
    scale_y_continuous(labels = function(x) paste0(x*100, "%")) +
    xlab("Neighborhood Group") +
    ylab("Percent")
```



#Yannian's Map
```{r}
#leaflet map

#creating the map
#get the shape file
library(leaflet)
r <- httr::GET('http://data.beta.nyc//dataset/0ff93d2d-90ba-457c-9f7e-39e47bf2ac5f/resource/35dd04fb-81b3-479b-a074-a27a37888ce7/download/d085e2f8d0b54d4590b1e7d1f35594c1pediacitiesnycneighborhoods.geojson')
nyc_neighborhoods <- rgdal::readOGR(content(r,'text'), 'OGRGeoJSON', verbose = F)

#Arrange Data
airbnb_data$predicted_race = as.factor(airbnb_data$predicted_race)
price_neighbour = airbnb_data %>%
  group_by(neighbourhood, neighbourhood_group) %>%
  summarise(count = length(neighbourhood),
            median_price = median(price),
            average_price = mean(price),
            dominant_race = names(table(predicted_race))[which.max(table(predicted_race))]) %>%#https://stackoverflow.com/questions/32766325/fastest-way-of-determining-most-frequent-factor-in-a-grouped-data-frame-in-dplyr
  arrange(neighbourhood)

race_median_borrough = airbnb_data %>%
  group_by(neighbourhood_group) %>%
  summarise(median_price = median(price),
            dominant_race = names(table(predicted_race))[which.max(table(predicted_race))],
            longitude = mean(longitude),
            latitude = mean(latitude))

#Add data to GeoJson file
units_count = 1:310
median_price_neighbour = 1:310
race_neighbour = c(rep("white", 60), rep("black", 60), rep("asian",60), rep("hispanic",60), rep("american indian",60),rep("no_data",10))
price_neighbour_count = price_neighbour$count
price_neighbour_median = price_neighbour$median_price
races = price_neighbour$dominant_race
names(price_neighbour_count) = levels(as.factor(price_neighbour$neighbourhood))
names(price_neighbour_median) = levels(as.factor(price_neighbour$neighbourhood))
names(races) = levels(as.factor(price_neighbour$neighbourhood))

for(i in 1:310){
  name = nyc_neighborhoods@data$neighborhood[[i]]
  value = price_neighbour_count[name]
  if(is.na(value)){
    units_count[i] = 0
  } else {
    units_count[i] = value
  }
}

for(i in 1:310){
  name = nyc_neighborhoods@data$neighborhood[[i]]
  value = price_neighbour_median[name]
  if(is.na(value)){
    median_price_neighbour[i] = 0
  } else {
    median_price_neighbour[i] = value
  }
}

for(i in 1:310){
  name = nyc_neighborhoods@data$neighborhood[[i]]
  value = races[name]
  if(is.na(value)){
    race_neighbour[i] = "no_data"
  } else {
    race_neighbour[i] = value
  }
}

nyc_neighborhoods@data$count = units_count
nyc_neighborhoods@data$median_price = median_price_neighbour
nyc_neighborhoods@data$dominant_race = as.character(race_neighbour)

nyc_neighborhoods.df = as.data.frame(nyc_neighborhoods)

#coloring functions
pal <- colorFactor(
  palette = topo.colors(5),
  domain = nyc_neighborhoods@data$borough)

pal1 <- colorNumeric(
  palette = "Reds",
  domain = nyc_neighborhoods@data$median_price_neighbour)

#popup labels
nyc_neighborhoods.df = as.data.frame(nyc_neighborhoods)
labels = sprintf("<strong>%s</strong><br/>Median Price: %g <br/>Dominant Race: %s",
                 nyc_neighborhoods.df$neighborhood, nyc_neighborhoods.df$median_price, nyc_neighborhoods.df$dominant_race) %>%
  lapply(htmltools::HTML)

labels1 = sprintf("<strong>%s</strong><br/> %s <br/>Median Price: %g <br/>Dominant Race: %s",
                  nyc_neighborhoods.df$borough, nyc_neighborhoods.df$neighborhood, nyc_neighborhoods.df$median_price, nyc_neighborhoods.df$dominant_race) %>%
  lapply(htmltools::HTML)

Manhattan_content = paste(sep = "",
                 "<b>Manhattan</b><br/>",
                 "Median Price: ", race_median_borrough$median_price[3],"<br/>",
                 "Predicted Dominant Race:", race_median_borrough$dominant_race[3])#https://rstudio.github.io/leaflet/popups.html

Bronx_content = paste(sep = "",
                      "<b>Bronx</b><br/>",
                      "Median Price: ", race_median_borrough$median_price[1],"<br/>",
                      "Predicted Dominant Race:", race_median_borrough$dominant_race[1])

Brooklyn_content = paste(sep = "",
                         "<b>Brooklyn</b><br/>",
                         "Median Price: ", race_median_borrough$median_price[2],"<br/>",
                         "Predicted Dominant Race:", race_median_borrough$dominant_race[2])

Queens_content = paste(sep = "",
                       "<b>Queens</b><br/>",
                       "Median Price: ", race_median_borrough$median_price[4],"<br/>",
                       "Predicted Dominant Race:", race_median_borrough$dominant_race[4])

Staten_Island_content = paste(sep = "",
      "<b>Staten Island</b><br/>",
      "Median Price: ", race_median_borrough$median_price[5],"<br/>",
      "Predicted Dominant Race:", race_median_borrough$dominant_race[5])

#making map
nyc_map = leaflet(nyc_neighborhoods) %>%
  addPolygons(fillColor = ~pal(borough),
              dashArray = "2",
              weight = 1,
              color = "black",
              fillOpacity = 0.5,
              group = "Borough",
              highlight = highlightOptions(
                weight = 5,
                color = "#666",
                dashArray = "",
                fillOpacity = 0.7,
                bringToFront = TRUE)) %>%
  addPolygons(fillColor = ~pal1(price_neighbour_median),
              dashArray = "2",
              weight = 1,
              color = "black",
              fillOpacity = 0.5,
              group = "Median Price",
              highlight = highlightOptions(
                weight = 5,
                color = "#666",
                dashArray = "",
                fillOpacity = 0.7,
                bringToFront = TRUE),
              label = labels,
              labelOptions = labelOptions(
                style = list("font-weight" = "normal", padding = "3px 8px"),
                textsize = "15px",
                direction = "auto")) %>%
  addLayersControl(baseGroups = c("Borough", "Median Price"),
                   options = layersControlOptions(collapsed = FALSE)) %>%
  addProviderTiles("CartoDB.Positron") %>%
  addLegend(pal = pal, values = ~borough, opacity = 0.5, title = NULL,
            position = "bottomright") %>%
  addLegend(pal = pal1, values = ~price_neighbour_median, opacity = 0.5, title = NULL,
            position = "bottomright") %>%
  addPopups(-73.98589201142906, 40.755771283, Manhattan_content,
            options = popupOptions(closeButton = TRUE,maxWidth = 100)) %>%
  addPopups(-73.8355080975089, 40.88371907524592, Bronx_content,
            options = popupOptions(closeButton = TRUE,maxWidth = 100)) %>%
  addPopups(-73.95201733179279,40.59818409943234,  Brooklyn_content,
            options = popupOptions(closeButton = TRUE,maxWidth = 100)) %>%
  addPopups(-73.73093696338323, 40.7184732562638, Queens_content,
            options = popupOptions(closeButton = TRUE,maxWidth = 100)) %>%
  addPopups( -74.181493, 40.552025, Staten_Island_content,
            options = popupOptions(closeButton = TRUE,maxWidth = 100))
nyc_map
#htmlwidgets::saveWidget(nyc_map, file = "nyc_map.html")

```

