---
title: "covid_analysis"
author: "Collin"
date: "5/17/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(caret)
library(tidyverse)
library(readxl)
library(forecast)

library(plotly)
library(httr)
library(rvest)
library(ggpubr)
library(quantmod)
# library(Hmisc)
# library(lfe)
# library(AER)
# library(forecast)
# library(astsa)
# library(aTSA)


#merge by state
#from nyt

us_counties <- read_csv("us-counties.csv")
us_counties
# us_counties = us_counties %>% 
#   group_by(county) %>% 
#   mutate(daily_deaths = deaths - lag(deaths,1)) %>% 
#   rename("total_deaths" = "deaths")

us_states = read_csv("us-states.csv")
us_states


#from cdc- merge nyt and cdc
cdc_vaccinations <-read_csv("Vaccine_Hesitancy_for_COVID-19__County_and_local_estimates.csv")
cdc_vaccinations = cdc_vaccinations %>% rename("fips" = `FIPS Code`)
cdc_vaccinations %>% head(10)



counties_vaccination_df = us_counties %>% mutate(fips = as.double(fips)) %>% left_join(cdc_vaccinations,by = "fips")



#THE dataframe to use for analysis
counties_vaccination_df = counties_vaccination_df %>% 
  group_by(state,county) %>% filter(county != "Unknown") %>% 
  filter(state != "Northern Mariana Islands") %>% 
  filter(state != "Virgin Islands") %>% 
  filter(state != "District of Columbia") %>% 
  mutate(daily_deaths = deaths - lag(deaths)) %>% 
  mutate(date = as.Date(date)) %>% 
  rename("total_deaths" = "deaths") %>% drop_na(daily_deaths)


counties_vaccination_df %>% arrange(date) %>% head(5)

counties_vaccination_df %>% drop_na(daily_deaths) %>% 
  group_by(state,county) %>% 
  dplyr::summarize(total_daily_deaths = sum(daily_deaths))
  
  

  
#bring in county population data:
#variables of interest: "POPESTIMATE2019", COUNTY
county_pop_data = readr::read_csv("co-est2019-alldata.csv")
county_pop_data = county_pop_data %>% mutate(fips = paste0(STATE,COUNTY))
county_pop_data = county_pop_data %>% rename("new_county_name" = "CTYNAME") %>% 
  select(new_county_name,POPESTIMATE2019)



counties_vaccination_df = counties_vaccination_df %>% mutate(new_county_name = paste(county," County"))
counties_vaccination_df %>% head(50) %>% select(county,state,fips,cases,total_deaths, new_county_name)

#merge county_pop_data into counties_vaccination_df so Ill have population data for each county
counties_vaccination_df = counties_vaccination_df %>% inner_join(county_pop_data, by = "new_county_name")
counties_vaccination_df

```


#State Level Analysis-Use this!
```{r}
#from new york times github
us_states = read_csv("us-states.csv")

california_data = us_states %>% filter(state == "California") %>% arrange(date) %>% 
  mutate(daily_deaths = deaths - lag(deaths)) %>% 
  mutate(date = as.Date(date)) %>% 
  rename("total_deaths" = "deaths") %>% drop_na(daily_deaths)
california_data

alabama_data = us_states %>% filter(state == "Alabama") %>% arrange(date) %>% 
  mutate(daily_deaths = deaths - lag(deaths)) %>% 
  mutate(date = as.Date(date)) %>% 
  rename("total_deaths" = "deaths") %>% drop_na(daily_deaths)


#Actual Data??
us_state_vaccinations = read_csv("us_state_vaccinations.csv")
us_state_vaccinations

#create vaccine data for California
california_vaccinations = us_state_vaccinations %>% filter(location == "California") %>% rename("state" = "location")
california_vaccinations

#create vaccine data for Alabama
alabama_vaccinations = us_state_vaccinations %>% filter(location == "Alabama") %>% 
  rename("state" = "location")


#california_vaccination data for model building, use this for california
california_vaccination_df = california_data %>% left_join(california_vaccinations, by= "date") %>% 
  select(date, state.x,fips,cases,total_deaths,daily_deaths,people_fully_vaccinated_per_hundred,total_vaccinations,total_distributed,people_vaccinated,share_doses_used) %>% rename("state" = "state.x") %>%
  mutate_at(vars(people_fully_vaccinated_per_hundred, share_doses_used), ~replace_na(., 0))
#fix data from 357 to 359
california_vaccination_df$people_fully_vaccinated_per_hundred[355] = .34
california_vaccination_df$people_fully_vaccinated_per_hundred[357:359] = rep(.52,3)
california_vaccination_df$share_doses_used[357:359] = rep(.302,3)
california_vaccination_df$people_fully_vaccinated_per_hundred[387] =3.26
california_vaccination_df$share_doses_used[387] =.722


#alabama_vaccination data for model building
alabama_vaccination_df = alabama_data %>% left_join(alabama_vaccinations, by= "date") %>% 
  select(date, state.x,fips,cases,total_deaths,daily_deaths,people_fully_vaccinated_per_hundred,total_vaccinations,total_distributed,people_vaccinated,share_doses_used) %>% rename("state" = "state.x")%>%
  mutate_at(vars(people_fully_vaccinated_per_hundred, share_doses_used), ~replace_na(., 0))

#fix some of the zeros:

alabama_vaccination_df$people_fully_vaccinated_per_hundred[307] = .19
alabama_vaccination_df$people_fully_vaccinated_per_hundred[309:310] = .28
alabama_vaccination_df$share_doses_used[309:310] = .226
alabama_vaccination_df$people_fully_vaccinated_per_hundred[339] = 2.79
alabama_vaccination_df$share_doses_used[339] = .634

alabama_vaccination_df

#check for negatives
california_vaccination_df %>% filter(daily_deaths < 0)

```
#Model Building
```{r}
california_vaccination_df
library(zoo)

alabama_vaccination_df
#create ts objects for both states:
california_ts = zoo(california_vaccination_df$daily_deaths, seq(from = as.Date("2020-01-26"), to = as.Date("2021-05-30"), by = 1))

alabama_ts = zoo(alabama_vaccination_df$daily_deaths, seq(from = as.Date("2020-03-14"), to = as.Date("2021-05-30"), by = 1))
# california_ts = ts(california_vaccination_df$daily_deaths,frequency = 365, start = c(2020,26))
plot(california_ts)
acf(california_ts) #not looking so stationary
pacf(california_ts) #gonna need a lot of AR lags


california_xreg_matrix = as.matrix(california_vaccination_df %>% select(people_fully_vaccinated_per_hundred,share_doses_used))
california_model = auto.arima(california_ts,xreg = california_xreg_matrix)
california_model$fitted


alabama_xreg_matrix = as.matrix(alabama_vaccination_df %>% select(people_fully_vaccinated_per_hundred,share_doses_used))
alabama_model = auto.arima(alabama_ts,xreg = alabama_xreg_matrix)
alabama_model



```



#Prediction
```{r}


```






#TEST
```{r}
#TEST TEST TEST
#test case should be 64 total deaths in Bibb County, Alabama
counties_vaccination_df %>% filter(state == "Alabama") %>% 
  filter(county == "Bibb") %>% select(county,total_deaths,daily_deaths) %>% drop_na(daily_deaths) %>% 
  dplyr::summarize(summed_daily_deaths = sum(daily_deaths))

vector1 = c(0,0,0,1,1,2,3,4)
vector2 = vector1 - lag(vector1)
vector2
```


## Find state with lowest vaccination rate (ignore)
```{r}


counties_vaccination_df %>% group_by(state) %>% 
  dplyr::summarize(lowest_vaccination_rate = min(mean(`Percent adults fully vaccinated against COVID-19`,na.rm = TRUE))) %>% arrange(lowest_vaccination_rate) #California with high vaccination rate, Georgia with the lowest average vaccination rate across counties

counties_vaccination_df$
```




# Time Series
```{r}
## Time series stuff

?forecast::accuracy() #potentially use this to evaluate accuracy of our model when we validate the model on test data
?ARMAacf
?arima #fits an arima model to a time series object
?arima.sim #simulates an arima model where you choose the parameters for ar and ma
?ARMAtoMA #converts an ARMA to an infinite MA process (by property of invertibility)
?sarima #fit a arima(p,d,q) with an xreg argument to provide other regressors
?arima





#establish time series object for daily deaths
?

counties_vaccination_df$L.daily_deaths <- Lag(counties_vaccination_df$daily_deaths, 1)
counties_vaccination_df$L2.daily_deaths <- Lag(counties_vaccination_df$daily_deaths, 2)
counties_vaccination_df$L3.daily_deaths <- Lag(counties_vaccination_df$daily_deaths, 3)

auto.arima(counties_vaccination_df$daily_deaths)
?auto.arima

difference1 <- counties_vaccination_df$daily_deaths - counties_vaccination_df$L.daily_deaths
difference2 <- counties_vaccination_df$L.daily_deaths - counties_vaccination_df$L2.daily_deaths
difference3 <- counties_vaccination_df$L2.daily_deaths - counties_vaccination_df$L3.daily_deaths

auto.arima(difference1)

death_model <- lm(data = counties_vaccination_df, difference1 ~ difference2 + difference3 + counties_vaccination_df$`Percent adults fully vaccinated against COVID-19` + counties_vaccination_df$`Estimated hesitant`)
summary(death_model)

#ARMA(2,1)
## Calls it an ARIMA(2,1,1 Process)
```



## Checking Stationarity Assumptions for each State
```{r}
#create a time series object for each state and check if its stationary 


states = unique(counties_vaccination_df$state)


# out = adf.test(daily_deaths_ts)
# unname(out$type1[1,3]) #loop over the row but keep 3rd column because thats the p-value
# str(out$type1)
# 
# str(out$type1[1,3])

#create empty dataframe
stationary_df = tibble(state = states, stationary_status = rep("stationary",length(states)) )
stationary_df

#LOOP TO DETERMINE WHICH STATES HAVE NON STATIONARY TIME SERIES
for(place in states){ 
  daily_deaths_ts = ts((counties_vaccination_df %>% filter(state== place))$daily_deaths, frequency = 1) #first create a ts object
  adf_out = adf.test(daily_deaths_ts) #conduct the augmented-dickey fuller test for stationarity on the time series object
  for(i in length(adf_out$type1[,3])){ #now loop through each lag of the adf.test output. if find a p-value > .05, conclude not stationary 
    if(unname(adf_out$type1[i,3]) > .05){
      stationary_df = stationary_df %>% mutate(stationary_status = case_when(
        state == place ~ "NOT STATIONARY",
        TRUE ~ as.character(stationary_status)
      ))
      next
      
    }
  }  
}
stationary_df %>% filter(stationary_status == "NOT STATIONARY") #District of Columbia only non-stationary 

```




#Model Construction (scratch this)
```{r}
#TS model without vaccination rates
counties_vaccination_df %>% filter(daily_deaths < 0)
#turn into dummies

state_dummies = as.factor(counties_vaccination_df$state)
state_quant = model.matrix(~state_dummies)
state_quant = state_quant[-1,]
state_quant

#create time series object out of daily deaths
daily_deaths_ts = ts(counties_vaccination_df$daily_deaths)
plot(daily_deaths_ts)

daily_deaths_ts
dim(state_quant)
no_vax_model = auto.arima(daily_deaths_ts, stationary = TRUE, xreg = c(state_quant)) #telling me different dimensions
no_vax_model


```





#Current TS work
```{r}
#Georgia Time series:
california_data = counties_vaccination_df %>% filter(state == "California") %>% 
  filter(daily_deaths > -1) %>% 
  filter(date >= "2020-03-03"	) %>% 
  group_by(date) %>% 
  dplyr::summarise(statewide_daily_deaths = sum(daily_deaths))
california_data


georgia_data = counties_vaccination_df %>% filter(state == "Georgia")%>% filter(daily_deaths > -1) %>% 
  group_by(date) %>% 
  dplyr::summarize(statewide_daily_deaths = sum(daily_deaths))
georgia_data
 #about 496 corrections -> negative daily death counts


georgia_ts = ts(georgia_data$statewide_daily_deaths)
georgia_ts
ggplot(data = georgia_data, mapping = aes(x = date, y = statewide_daily_deaths))+
  geom_line()+theme_minimal()

#test for stationary
adf.test(georgia_ts) #is stationary
#acf to confirm, looks not stationary


#try log-differencing transformation
georgia_data = georgia_data %>% 
  mutate(lag_statewide_daily_deaths = lag(statewide_daily_deaths)) %>% 
  mutate(logdiff_statewide_dd = log(statewide_daily_deaths) - log(lag_statewide_daily_deaths))
georgia_data


```






#TEST
```{r}
counties_vaccination_df

#TEST TEST TEST
#test case should be 64 total deaths in Bibb County, Alabama
counties_vaccination_df %>% filter(state == "Alabama") %>% 
  filter(county == "Bibb") %>% select(county,total_deaths,daily_deaths) %>% drop_na(daily_deaths) %>% 
  dplyr::summarize(total_daily_deaths = sum(daily_deaths))

vector1 = c(0,0,0,1,1,2,3,4)
vector2 = vector1 - lag(vector1)
vector2
```


```{r}
#attempt at whole US to get an idea of the overall picture


#how many counties are there? 1930
counties_vaccination_df %>% group_by(county) %>% 
  summarize(number_of_counties = n_distinct(county)) %>% arrange(desc(number_of_counties))
#55 states (includes territories like Guam)



#This should verify the data is correct-> no more negativess
sum_daily_deaths = counties_vaccination_df %>% 
  group_by(state,county) %>% 
  dplyr::summarize(sum_daily_deaths = sum(daily_deaths))
sum_daily_deaths %>% filter(sum_daily_deaths < 0)



```






#Ignore
```{r}

#IGNORE
html = read_html("https://data.cdc.gov/NCHS/Provisional-COVID-19-Death-Counts-in-the-United-St/kn79-hsxy")

stuff = xml2::read_html("https://data.cdc.gov/NCHS/Provisional-COVID-19-Death-Counts-in-the-United-St/kn79-hsxy")
library(rvest)
library(xml2)
ca_counties = read_html("https://www.nytimes.com/interactive/2021/us/california-covid-cases.html") %>% 
  html_node("table.g-table.super-table.withchildren") %>% html_table()
ca_counties

?html_nodes
```




